### ISSUE TITLE
The device has no langid error when icon used

### ISSUE THREAD

**Issue by CozmoCyke** [jnweiger/led-name-badge-ls32#25]
Hello,

The "hello world" example is running ok : )
But I have an error when I want to use builtin icon : (

Windows 7 , Python 3.5.4 64 bits
 

D:\dev\sertronics\led-name-badge-ls32-master>python led-badge-11x44.py :ball:
Traceback (most recent call last):
  File "led-badge-11x44.py", line 475, in <module>
    print("using [%s %s] bus=%d dev=%d" % (dev.manufacturer, dev.product, dev.bu
s, dev.address))
  File "C:\Python35\lib\site-packages\usb\core.py", line 852, in manufacturer
    self._manufacturer = util.get_string(self, self.iManufacturer)
  File "C:\Python35\lib\site-packages\usb\util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid

**Comment by beta-tester** [comment]
i have the same error...
first i tried the example with -m 6. this went good.
after that i tried -m 1, followed by -m 2, ... now i always get that lang id error event when not usinf -m and -s option...
```
pi@raspberry:~ $ sudo python3 ~/led-name-badge-ls32/led-badge-11x44.py -m 6 -s 8 "Hello World!"
using [LSicroelectronics LS32 Custm HID] bus=1 dev=4
Type: 11x44

pi@raspberry:~ $ sudo python3 ~/led-name-badge-ls32/led-badge-11x44.py -m 1 -s 8 "Hello World!"
Traceback (most recent call last):
  File "/home/pi/led-name-badge-ls32/led-badge-11x44.py", line 475, in <module>
    print("using [%s %s] bus=%d dev=%d" % (dev.manufacturer, dev.product, dev.bus, dev.address))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 852, in manufacturer
    self._manufacturer = util.get_string(self, self.iManufacturer)
  File "/usr/lib/python3/dist-packages/usb/util.py", line 325, in get_string
    langid
  File "/usr/lib/python3/dist-packages/usb/control.py", line 173, in get_descriptor
    data_or_wLength = desc_size)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error

pi@raspberry:~ $ sudo python3 ~/led-name-badge-ls32/led-badge-11x44.py -m 2 -s 8 "Hello World!"
Traceback (most recent call last):
  File "/home/pi/led-name-badge-ls32/led-badge-11x44.py", line 475, in <module>
    print("using [%s %s] bus=%d dev=%d" % (dev.manufacturer, dev.product, dev.bus, dev.address))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 852, in manufacturer
    self._manufacturer = util.get_string(self, self.iManufacturer)
  File "/usr/lib/python3/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid

```
