### ISSUE TITLE
Using : in text is not Posible

### ISSUE THREAD

**Issue by seppal123** [jnweiger/led-name-badge-ls32#31]
Hi all 

I would like to use the LED Badge as Status Monitor for Linux.
All i want is to output the uptime command to the LED. see example below.
Problem is,  that the ":" characters have a buildin funktion for the bitmaps so i cannot show a Timestamp.
Is there a way that i can escape the ":" character so that they are not interpreted as Picture ?

Thanks is advance, and a happy new year 2021
Ciao
   Sandro

---example--
sandro@schleppy:~/led-name-badge-ls32$ uptime
 11:16:27 up 26 min,  1 user,  load average: 0,56, 0,38, 0,21

sandro@schleppy:~/led-name-badge-ls32$ python3 ./led-badge-11x44.py "11:07:53 up 17 min, 1 user, load average: 0,00, 0,05, 0,09"
using [LSicroelectronics LS32 Custm HID] bus=1 dev=13
Traceback (most recent call last):
  File "./led-badge-11x44.py", line 487, in <module>
    msgs.append(bitmap(arg))
  File "./led-badge-11x44.py", line 360, in bitmap
    return bitmap_text(arg)
  File "./led-badge-11x44.py", line 315, in bitmap_text
    (b,n) = bitmap_char(c)
  File "./led-badge-11x44.py", line 284, in bitmap_char
    return bitmap_preloaded[ord(ch)]
IndexError: list index out of range

**Comment by derpicknicker1** [comment]
Use two colons to escape `::`

**Comment by SpotlightKid** [comment]
This should be documented in the readme and the `--help` output.
