### ISSUE TITLE
ValueError: Invalid endpoint address 0x1

### ISSUE THREAD

**Issue by ghosty-be** [jnweiger/led-name-badge-ls32#36]
Tried on Linux Mint 20.3 and 21 (debian - ubuntu based):
install python3-usb through apt, python3-pil was already installed by default.
installed the udev rule etc
Device: NB1144
tried running with and without sudo, even directly as root.

When I try the example I get the following error:
`./led-badge-11x44.py "Hello" 
using [wch.cn CH583] bus=5 dev=10
Type: 11x44
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/usb/core.py", line 223, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./led-badge-11x44.py", line 523, in <module>
    dev.write(1, buf[i*64:i*64+64])
  File "/usr/lib/python3/dist-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 231, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x1
`

**Comment by ghosty-be** [comment]
according to this:
https://github.com/pyusb/pyusb/blob/master/docs/tutorial.rst
this looks like a better idea, to detect the endpoint, rather than hard code it?
```
$ diff led-badge-11x44.py led-badge-11x44.py.orig 
521,530d520
<   cfg = dev.get_active_configuration()
<   intf = cfg[(0,0)]
< 
<   ep = usb.util.find_descriptor(
<       intf,
<       # match the first OUT endpoint
<       custom_match = \
<       lambda e: \
<           usb.util.endpoint_direction(e.bEndpointAddress) == \
<           usb.util.ENDPOINT_OUT)
533,534c523
<     #dev.write(2, buf[i*64:i*64+64])
<     ep.write(buf[i*64:i*64+64])
---
>     dev.write(1, buf[i*64:i*64+64])
```

**Comment by ids93216** [comment]
I have same problem here, after editing dev.write, it works! Thank you

**Comment by KaeTuuN** [comment]
@ghosty-be Maybe you can make a PR for that so @jnweiger may merge it! :-)

**Comment by dirkhillbrecht** [comment]
I'd like to stress that this patch fixes the described issue for the usb.core code path on Linux. However, newer versions of the hardware do not seem to work with this approach generally any more, even with the fix. You need to switch to pyhidapi access and apply a fix to make it working again. Pull Request pending.

**Comment by azrdev** [comment]
PR: https://github.com/jnweiger/led-name-badge-ls32/pull/42

**Comment by sarduri** [comment]
Changeing Line in led-badge-11x44.py to
dev.write(2, buf[i * 64:i * 64 + 64])
But only once. Then I have to desconnect the device and reconnect it again. Is there a way to avoid this behavior?

**Comment by jnweiger** [comment]
#42 is merged.

**Comment by bensartori** [comment]
The point with the endpoint number is closely connected to #37, because these devices seem to use Endpoint 2 instead of 1. They also use another USB-to-serial chip. My idea is to automatically use the only endpoint available, instead of a fixed one. I'l try to implement this somewhen in the next weeks (cannot promise...)

**Comment by bensartori** [comment]
Hello ghost.be, oh, I have overseen that you already did a patch as proposal. I'll try it soon.

**Comment by fcartegnie** [comment]
Libusbhid does not seems to set-up easily

I have a simpler workaround for now, without hardcoding
see https://github.com/fossasia/led-name-badge-ls32/commit/ae7195e94318ab711147173b081df2dd2e59fd12
