### ISSUE TITLE
operation time out on send multiple packets

### ISSUE THREAD

**Issue by mljack** [jnweiger/led-name-badge-ls32#38]
The badge hangs if I send more than one packet. Got following errors:

[root@alarmpi led-name-badge-ls32]# python2 ./led-badge-11x44.py "Hello world!"
using [LSicroelectronics LS32 Custm HID] bus=1 dev=98
Type: 11x44
packet 0
packet 1
packet 2
Traceback (most recent call last):
  File "./led-badge-11x44.py", line 524, in <module>
    dev.write(1, buf[i*64:i*64+64])
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 948, in write
    self.__get_timeout(timeout)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 842, in intr_write
    timeout)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 920, in __write
    _check(retval)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

I have to unplug and re-plug it to get it reset to normal.

I found the bmpbadge application also read some bytes from endpoint 81. Would that be the missing pieces?

**Comment by mljack** [comment]
I resolve the hang.
1. Add an extra 64 bytes read from 0x81 after each write.
2. Read another 64 bytes in the end
3. Finally DO NOT forget release the device with dev.reset(). Somehow, it still hang in next string upload if only call usb.util.dispose_resources(dev)
