### ISSUE TITLE
Under Mac Access Denied

### ISSUE THREAD

**Issue by AnnabelleLee1987** [jnweiger/led-name-badge-ls32#6]
Stacktrace:

python ./led-badge-11x44.py "Hello World"
using [LSicroelectronics LS32 Custm HID] bus=20 dev=3
Traceback (most recent call last):
  File "./led-badge-11x44.py", line 374, in <module>
    dev.write(1, buf[i*64:i*64+64])
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Users/anna-katharinarausch/dev/led-badge-44x11/girls_env/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

**Comment by jnweiger** [comment]
@AnnabelleLee1987 this should be solved by #4, please test!

**Comment by jnweiger** [comment]
Closing. We assume this case now works well.

**Comment by rkachowski** [comment]
I get the same error on 10.14 macos.

```
python3 ./led-badge-11x44.py "heellllo weorld"
using [LSicroelectronics LS32 Custm HID] bus=20 dev=9
Type: 11x44
Traceback (most recent call last):
  File "./led-badge-11x44.py", line 498, in <module>
    dev.write(1, buf[i*64:i*64+64])
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by jnweiger** [comment]
Hmm, does it work when you try with sudo or as root user?
